env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint  # for supporting dynamic import()
globals:
  Atomics: readonly
  BigInt: readonly
  SharedArrayBuffer: readonly
  globalThis: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns:
  - node_modules/
  - /out/
  - /polyfill/test262/
  # Specific vendored or generated files
  - /docs/mermaid.js
  - /docs/playground.js
  - /docs/prism.js
  - /polyfill/index.js
  - /polyfill/script.js
rules:
  curly:
    - error
    - multi-line
  indent:
    - error
    - 2
    - SwitchCase: 1
  object-curly-spacing:
    - error
    - always
  semi: error
overrides:
  - files:
      - polyfill/test/Absolute/**/*.js
      - polyfill/test/Date/**/*.js
      - polyfill/test/DateTime/**/*.js
      - polyfill/test/Duration/**/*.js
      - polyfill/test/MonthDay/**/*.js
      - polyfill/test/Temporal/**/*.js
      - polyfill/test/Time/**/*.js
      - polyfill/test/TimeZone/**/*.js
      - polyfill/test/YearMonth/**/*.js
    globals:
      Temporal: readonly
      assert: readonly
      verifyProperty: readonly
