language: node_js
node_js: 12
before_install:
- cd polyfill/
script:
- node --experimental-modules ./test/regex.mjs
- node --experimental-modules ./test/date.mjs
- node --experimental-modules ./test/time.mjs
- npm run build
deploy:
  local_dir: out/
  target_branch: gh-pages
  keep_history: true
  provider: pages
  skip_cleanup: true
  github_token: "$GH_ACCESS_TOKEN"
  committer_from_gh: true
  on:
    branch: main
env:
  global:
    secure: L3ky+TrWkW4UymNlKsZ+LJ52lPLwS/Qr/7VbYv3fnYrVQeXQZ7AsS9279Vyb0pqpUm15Qt49SMWmwTkF/G+oyxWRsAReNlumOnY+sCF0twb8blLghJ+wmfh/QBAoGdNxbIpKA+ULNyr8uFN0dBHLLj+j8bAz1gIm9i/VO7u9dcHF2WBDOQN5JJxLLGX9Omh/Ytj/LETt3WIPd4T2JzotcqcwXQVlD8SDrR4QP15VwNvWyaBy+49Lv9GTVAbui5/kEsvhjC6SFdPDEk+Z0qapp7fRKdmJvcKBmt7m/IL1QI2k9HdQfbf3Au9v8mVRuCMR/en1iakcp8nkIXSw8RLZaz9fHh69aN8IWmQg6bx1/kl6VK19MhbHOtsK89qQt+zPKUcXZsMvxBeWA695rP6Ukk1HPZ08TcHomW1dJguqHVYChYUFK2SnhOsFhHaClYnDC4xwn0CvP5ExBFWg+LSEyqZCan08pyhRVbRmn6pmRDnsW0NlglB+KHwvfg9o9XzGDDWEMgHot5yg3be3ZhSZRfIOlDW3uzoKs05OVCIkgVwtbjKTun0ZKWTRRDtgLE/m40t9VnmHlUKvp5NgtyvZtNFXTXvJjYcSjJWM6ArxKJEDfBEsLTMMmvTrOaF5275m2GqAAD4V99qlru54JHvcQcamfntdqa9jZVpYIs7yUwI=
