name: Run tests
on: pull_request
jobs:
  test-polyfill:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run codecov:tests
  test-test262:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run codecov:test262
  test-cookbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run test-cookbook
