name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-polyfill-node15:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run codecov:tests
  test-polyfill-node14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run codecov:tests
  test-polyfill-node12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run codecov:tests
  test-test262:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run codecov:test262
  test-cookbook-node15:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run test-cookbook
  test-cookbook-node14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run test-cookbook
  test-cookbook-node12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run test-cookbook
